# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cpfcalui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cpfcalui(object):
    def setupUi(self, cpfcalui):
        cpfcalui.setObjectName("cpfcalui")
        cpfcalui.resize(885, 979)
        self.label = QtWidgets.QLabel(cpfcalui)
        self.label.setGeometry(QtCore.QRect(30, 10, 301, 81))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(cpfcalui)
        self.tabWidget.setGeometry(QtCore.QRect(30, 70, 451, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 231, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(250, 10, 171, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 231, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 40, 101, 22))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 40, 101, 22))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 70, 71, 22))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_5.setObjectName("label_5")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(120, 120, 301, 121))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 119))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 300, 121))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(280, 250, 61, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(120, 253, 31, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(153, 250, 31, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(190, 253, 51, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 250, 31, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 250, 61, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 161, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 290, 61, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 330, 181, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 330, 91, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(290, 330, 61, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(360, 330, 61, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 370, 211, 16))
        self.label_10.setObjectName("label_10")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(230, 370, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 400, 131, 16))
        self.label_11.setObjectName("label_11")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 400, 73, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 440, 211, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_12 = QtWidgets.QLabel(cpfcalui)
        self.label_12.setGeometry(QtCore.QRect(20, 610, 461, 251))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("photo_2018-10-01_20-06-39.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        
    


        self.retranslateUi(cpfcalui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cpfcalui)
    

    def retranslateUi(self, cpfcalui):
        _translate = QtCore.QCoreApplication.translate
        cpfcalui.setWindowTitle(_translate("cpfcalui", "Dialog"))
        self.label.setText(_translate("cpfcalui", "CPF CALCULATOR"))
        self.label_2.setText(_translate("cpfcalui", "Target Excess Amount For Withdrawal :"))
        self.lineEdit.setText(_translate("cpfcalui", "$"))
        self.label_3.setText(_translate("cpfcalui", "Current amount in accounts :"))
        self.lineEdit_2.setText(_translate("cpfcalui", "OA"))
        self.lineEdit_3.setText(_translate("cpfcalui", "SA"))
        self.label_4.setText(_translate("cpfcalui", "Current Age :"))
        self.label_5.setText(_translate("cpfcalui", "Salary at age :"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(True)
        item = self.listWidget.item(0)
        item.setText(_translate("cpfcalui", "Demo"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("cpfcalui", "Add"))
        self.label_6.setText(_translate("cpfcalui", "Age :"))
        self.label_7.setText(_translate("cpfcalui", "Salary :"))
        self.pushButton_2.setText(_translate("cpfcalui", "Del"))
        self.label_8.setText(_translate("cpfcalui", "Top up amount per year :"))
        self.lineEdit_7.setText(_translate("cpfcalui", "$"))
        self.label_9.setText(_translate("cpfcalui", "HDB loan payment (Monthly) : "))
        self.lineEdit_8.setText(_translate("cpfcalui", "No. of months"))
        self.lineEdit_9.setText(_translate("cpfcalui", "Age"))
        self.lineEdit_10.setText(_translate("cpfcalui", "$"))
        self.label_10.setText(_translate("cpfcalui", "Retirement account savings @ 55 :"))
        self.comboBox.setItemText(0, _translate("cpfcalui", "BRS"))
        self.comboBox.setItemText(1, _translate("cpfcalui", "FRS"))
        self.comboBox.setItemText(2, _translate("cpfcalui", "ERS"))
        self.label_11.setText(_translate("cpfcalui", "Monthly payout plan :"))
        self.comboBox_2.setItemText(0, _translate("cpfcalui", "SP"))
        self.comboBox_2.setItemText(1, _translate("cpfcalui", "BP"))
        self.comboBox_2.setItemText(2, _translate("cpfcalui", "EP"))
        self.pushButton_3.setText(_translate("cpfcalui", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("cpfcalui", "You"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("cpfcalui", "Spouse"))
        self.pushButton_2.clicked.connect(self.delete_item)
        self.pushButton.clicked.connect(self.add_item)
        


    def delete_item(self):
        self.listWidget.takeItem(self.listWidget.currentRow())
    def add_item(self):
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item.setText('Age:' + self.lineEdit_5.text() + ' Salary: $' + self.lineEdit_6.text())
        self.listWidget.update()
        self.listWidget.repaint()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cpfcalui = QtWidgets.QDialog()
    ui = Ui_cpfcalui()
    ui.setupUi(cpfcalui)
    cpfcalui.show()
    cpfcalui.setWindowTitle("CPF Calculator")
    cpfcalui.setWindowIcon(QtGui.QIcon("O_m2BLlJ_400x400.png"))
    sys.exit(app.exec_())

